routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'index'])->name('home');

Route::get('/register', [AuthController::class, 'register'])->name('register');
Route::post('/welcome', [AuthController::class, 'welcome'])->name('welcome');

Route::get('/data-tables', [IndexController::class, 'dataTable'])->name('data-table');

Route::prefix('cast')->name('cast.')->group(function () {
    Route::get('/', [CastController::class, 'index'])->name('index');

    Route::middleware(['auth'])->group(function () {
        Route::get('/create', [CastController::class, 'create'])->name('create');
        Route::post('/', [CastController::class, 'store'])->name('store');
        Route::get('/{cast}/edit', [CastController::class, 'edit'])->name('edit');
        Route::put('/{cast}', [CastController::class, 'update'])->name('update');
        Route::delete('/{cast}', [CastController::class, 'destroy'])->name('destroy');
    });
    Route::get('/{cast}', [CastController::class, 'show'])->name('show');
});

Auth::routes(['verify' => false, 'reset' => false, 'confirm' => false]);

app/Models/Cast.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property integer $id
 * @property string $nama
 * @property integer $umur
 * @property string $bio
 * @property string $created_at
 * @property string $updated_at
 * @property Peran[] $perans
 */
class Cast extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['nama', 'umur', 'bio', 'created_at', 'updated_at'];

    /**
     * Has many peran
     * 
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function perans()
    {
        return $this->hasMany(Peran::class);
    }
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cast;
use Illuminate\Http\Request;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $casts = Cast::all();
        return view('cast.index', compact('casts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cast.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedCast = $request->validate([
            'nama' => 'required',
            'umur' => 'required|numeric',
            'bio' => 'required'
        ]);
        Cast::create($validatedCast);
        return redirect()->route('cast.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function show(Cast $cast)
    {
        return view('cast.show', compact('cast'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function edit(Cast $cast)
    {
        return view('cast.edit', compact('cast'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cast $cast)
    {
        $validatedCast = $request->validate([
            'nama' => 'required',
            'umur' => 'required|numeric',
            'bio' => 'required'
        ]);
        $cast->update($validatedCast);
        return redirect()->route('cast.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cast $cast)
    {
        $cast->delete();
        return redirect()->route('cast.index');
    }
}

resources/views/cast/create.blade.php
@extends('layouts.app')

@section('content')
<h2>Tambah Data</h2>
<form action="{{ route('cast.store') }}" method="POST">
    @csrf
    <div class="form-group">
        <label for="nama">Nama</label>
        <input type="text" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama">
        @error('nama')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="umur">Umur</label>
        <input type="number" class="form-control" name="umur" id="umur" placeholder="Masukkan Body">
        @error('umur')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="bio">Bio</label>
        <textarea name="bio" id="bio" class="form-control" cols="30" rows="10" placeholder="Masukkan Bio"></textarea>
        @error('bio')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary">Tambah</button>
</form>
@endsection

resources/views/cast/edit.blade.php
@extends('layouts.app')

@section('content')
<div>
    <h2>Edit Cast {{$cast->id}}</h2>
    <form action="{{ route('cast.update', $cast->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" class="form-control" name="nama" value="{{$cast->nama}}" id="nama"
                placeholder="Masukkan Nama">
            @error('nama')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="umur">Umur</label>
            <input type="number" class="form-control" name="umur" value="{{$cast->umur}}" id="umur"
                placeholder="Masukkan Body">
            @error('umur')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="bio">Bio</label>
            <textarea name="bio" id="bio" cols="30" class="form-control" rows="10" placeholder="Masukkan Bio">{{$cast->bio}}</textarea>
            @error('bio')
            <div class="alert alert-danger">
                {{ $message }}
            </div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/cast/index.blade.php
@extends('layouts.app')

@section('content')
<a href="{{ route('cast.create') }}" class="btn btn-primary mb-3">Tambah</a>
<table class="table">
    <thead class="thead-light">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Nama</th>
        <th scope="col">Umur</th>
        <th scope="col">Bio</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($casts as $key=>$value)
            <tr>
                <td>{{ $key + 1 }}</th>
                <td>{{ $value->nama }}</td>
                <td>{{ $value->umur }}</td>
                <td>{{ $value->bio }}</td>
                <td>
                    <a href="{{ route('cast.show', $value->id) }}" class="btn btn-sm btn-info">Show</a>
                    <a href="{{ route('cast.edit', $value->id) }}" class="btn btn-sm btn-primary">Edit</a>
                    <form action="{{ route('cast.destroy', $value->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <input type="submit" onclick="return confirm('Delete?')" class="btn btn-sm btn-danger" value="Delete">
                    </form>
                </td>
            </tr>
        @empty
            <tr colspan="3">
                <td>No data</td>
            </tr>  
        @endforelse              
    </tbody>
</table>
@endsection

resources/views/cast/show.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('cast.index')}}" class="btn btn-primary btn-sm"><-Back</a>
    <h2>Show Cast {{$cast->id}}</h2>
    <h4>{{$cast->nama}}</h4>
    <p>{{$cast->umur}}</p>
    <p>{{$cast->bio}}</p>
@endsection